# Generated by Django 3.2.6 on 2021-09-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Experience',
        ),
        migrations.AddField(
            model_name='post',
            name='CompantName',
            field=models.TextField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='ctc',
            field=models.IntegerField(default=0),
        ),
    ]
