# Generated by Django 3.2.6 on 2021-09-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_post_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='CompantName',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
