# Generated by Django 3.2.6 on 2021-09-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_post_compantname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Experience',
            field=models.TextField(max_length=540),
        ),
    ]
