# Generated by Django 3.2.6 on 2021-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
