# Generated by Django 3.2.6 on 2021-09-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_post_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dificulty',
            field=models.CharField(default='Intermediate', max_length=15),
        ),
    ]
