# Generated by Django 3.2.6 on 2021-09-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_post_dificulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dificulty',
            new_name='Difficulty',
        ),
    ]
