# Generated by Django 3.2.6 on 2021-09-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_rename_compantname_post_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Experience',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
