# Generated by Django 3.2.6 on 2021-09-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_post_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Experience',
            field=models.TextField(max_length=1000),
        ),
    ]
