# Generated by Django 3.2.6 on 2021-09-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20210926_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Difficulty',
            field=models.CharField(choices=[('Ease', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Intermediate', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.CharField(choices=[('cse', 'Cse'), ('Ece', 'Ece'), ('Eee', 'Eee'), ('IS', 'IS'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Chemical', 'Chemical')], default='Cse', max_length=20),
        ),
    ]
